### ISSUE TITLE
Spotify-Linux on Ubuntu 14.04 doesn't load

### ISSUE THREAD

**Issue by scottwarren** [jazzpi/spotify-linux#1]
I get an error on load of the package:

**Atom Version**: 0.188.0
**System**: linux 3.16.0-33-generic
**Thrown From**: 'packages' package, vundefined
### Stack Trace

Failed to activate the spotify-linux package

```
At Module did not self-register.

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at bindings (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket/lib/abstract_socket.js:4:34)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at createStream (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:45:19)
  at createConnection (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:70:30)
  at Function.module.exports.createClient (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:130:20)
  at Function.module.exports.sessionBus (/home/scott/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:141:25)
  at new SpotifyState (/home/scott/.atom/packages/spotify-linux/lib/spotify-state.coffee:11:27)
  at Object.module.exports.activate (/home/scott/.atom/packages/spotify-linux/lib/spotify-linux.coffee:20:14)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:461:21)
  at /usr/share/atom/resources/app/src/package-manager.js:334:19
  at /usr/share/atom/resources/app/src/config.js:631:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:793:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:608:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:224:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app/src/config.js:402:12)
  at Package.module.exports.Package.enable (/usr/share/atom/resources/app/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:162:14)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:209:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
     -0:46.9 command-palette:toggle (atom-text-editor.editor)
  4x -0:45.5 core:move-down (atom-text-editor.editor.mini)
     -0:44.5 core:confirm (atom-text-editor.editor.mini)
     -0:44.5 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:16.8 core:backspace (atom-text-editor.editor.mini)
     -0:16.4 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "/home/scott/projects"
  }
}
```
### Installed Packages

``` coffee
# User
.apm, vundefined
color-picker, v1.5.0
docblockr, v0.6.3
editorconfig, v0.3.3
keybinding-cheatsheet, v0.0.8
language-twig, v1.6.0
linter, v0.12.0
packages, vundefined
project-manager, v1.15.5
ruler, v0.2.3
seti-ui, v0.6.3
spotify-linux, v0.2.1

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
It looks like the `dbus-native` package is installing `abstract-socket` again for some reason.

Could you look into `~/.atom/packages/spotify-linux/node_modules` and tell me if there is a `abstract-socket` folder in there? If there is, please upload the `package.json` to Gist or something and post a link here. Otherwise, please upload a Gist of `~/.atom/packages/spotify-linx/node_modules/dbus-native/node_modules/abstract-socket/package.json`.

Thanks! :smiley:

**Comment by scottwarren** [comment]
This is installed on my work computer - I will have to check tomorrow -
thanks for the reply :-)

**Comment by jazzpi** [comment]
In the meantime, I've created a PR at sidorares/node-dbus#65 which should fix this issue even if it magically installs `abstract-socket` twice.

**Comment by scottwarren** [comment]
Thanks :smiley:

**Comment by scottwarren** [comment]
thanks for following this up :-) I will confirm tomorrow if this fixes it for me :)

**Comment by jazzpi** [comment]
Great, thanks :smile:
The close by commit was more or less accidental, but this should really fix it, so I'll just leave this closed unless it still doesn't work.

**Comment by scottwarren** [comment]
No worries :+1:

**Comment by scottwarren** [comment]
Yep just confirmed this works :) thanks for the quick fix :dancers:
