### ISSUE TITLE
Cannot find module 'abstract-socket'

### ISSUE THREAD

**Issue by luisgagocasas** [jazzpi/spotify-linux#13]
Error: Cannot find module 'abstract-socket'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at createStream (/home/luis/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:49:23)
    at createConnection (/home/luis/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:84:30)
    at Function.module.exports.createClient (/home/luis/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:144:20)
    at Function.module.exports.sessionBus (/home/luis/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:155:25)
    at new SpotifyState (/home/luis/.atom/packages/spotify-linux/lib/spotify-state.coffee:11:27)
    at Object.activate (/home/luis/.atom/packages/spotify-linux/lib/spotify-linux.coffee:20:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by josemarcosrf** [comment]
I solved by installing [abstract-socket](https://www.npmjs.com/package/abstract-socket), opening a terminal and executing:
```bash
    npm i abstract-socket
```

Restarting Atom, and all working.
Hope it helps.
