### ISSUE TITLE
Failed to load the spotify-linux package

### ISSUE THREAD

**Issue by decker-brower** [jazzpi/spotify-linux#2]
I get this error when trying to install the package.

**Atom Version**: 0.187.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [spotify-linux](https://github.com/jazzpi/spotify-linux) package, v0.2.1
### Stack Trace

Failed to load the spotify-linux package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/decker/.atom/packages/spotify-linux/lib/spotify-state.coffee:7:13)
    at Object.<anonymous> (/home/decker/.atom/packages/spotify-linux/lib/spotify-state.coffee:177:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "/home/decker/Projects",
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.7.1
color-picker, v1.5.0
file-icons, v1.5.2
git-projects, v1.12.0
git-tab-status, v1.6.0
highlight-selected, v0.9.1
minimap, v4.7.1
regex-railroad-diagram, v0.7.1
seti-syntax, v0.3.3
spotify-linux, v0.2.1

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
My bad, I thought `event-kit` was part of the Atom core and automatically installed. This should be fixed in version 0.2.2 by adding `event-kit` as a dependency. Can you test this?

**Comment by decker-brower** [comment]
perfect! thanks man. tested on linux with Atom v0.187.0

**Comment by jazzpi** [comment]
Great! :smile:
