### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by decker-brower** [jazzpi/spotify-linux#3]
**Steps to reproduce:**
1. update to latest version of Atom

**Atom Version**: 0.192.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [spotify-linux](https://github.com/jazzpi/spotify-linux) package, v0.2.3
### Stack Trace

Failed to activate the spotify-linux package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at bindings (/home/decker/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/decker/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket/lib/abstract_socket.js:4:34)
    at Module._compile (module.js:452:26)
```
### Commands

```
  2x -0:58.8 core:backspace (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "/home/decker/Projects",
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "spotify-linux": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.10.0
color-picker, v1.6.0
file-icons, v1.5.4
git-projects, v1.13.0
git-tab-status, v1.7.0
highlight-selected, v0.9.1
language-jade, v0.4.0
minimap, v4.7.6
regex-railroad-diagram, v0.7.4
seti-syntax, v0.3.3
spotify-linux, v0.2.3

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
I think this might be related to `atom-shell` now being `electron` and thus a version change (not sure about that though).

Anyways, it seems to be fixed if you go to `~/.atom/packages/spotify-linux`, delete the `node_modules` directory and run `apm install` so it installs the packages for the proper version.

**Comment by jazzpi** [comment]
Can you confirm whether this works?

**Comment by decker-brower** [comment]
deleted node_modules, ran apm install and apm rebuild-module-cache. now it works again : )

Thanks.
