### ISSUE TITLE
Failed to activate the spotify-linux package

### ISSUE THREAD

**Issue by LedBass** [jazzpi/spotify-linux#4]
Running Ubuntu 14.04

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [spotify-linux](https://github.com/jazzpi/spotify-linux) package, v0.2.3
### Stack Trace

Failed to activate the spotify-linux package

```
At Cannot find module 'abstract-socket'

Error: Cannot find module 'abstract-socket'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at createStream (/home/ledbass/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:45:19)
  at createConnection (/home/ledbass/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:70:30)
  at Function.module.exports.createClient (/home/ledbass/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:130:20)
  at Function.module.exports.sessionBus (/home/ledbass/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:141:25)
  at new SpotifyState (/home/ledbass/.atom/packages/spotify-linux/lib/spotify-state.coffee:11:27)
  at Object.module.exports.activate (/home/ledbass/.atom/packages/spotify-linux/lib/spotify-linux.coffee:20:14)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:222:19)
  at /usr/share/atom/resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -6:19.1.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {},
  "spotify-linux": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v1.7.0
spotify-linux, v0.2.3

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
How did you encounter this error? Did the package work before? Is it reproducible?

**Comment by LedBass** [comment]
No, I've just installed it and then the error appeared

Yes it is reproducible, install the 64 .deb ATOM version on an Ubuntu 14.04
64-bit, run it, search for Spotify and install the package, it'll bug
during the installation showing this stack trace, it shows as installed
later, but isn't working.

Also, I'm running the native Spotify client here

**Comment by jazzpi** [comment]
Whoops sorry, got lost in my inbox... Strange, I cannot reproduce this error although I've basically got the same setup. What happens if you run `npm install abstract-socket` in a terminal?

**Comment by jazzpi** [comment]
Bump @LedBass
