### ISSUE TITLE
Failed to activate the spotify-linux package

### ISSUE THREAD

**Issue by Yhozen** [jazzpi/spotify-linux#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: elementary OS
**Thrown From**: Atom Core
### Stack Trace

Failed to activate the spotify-linux package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at bindings (/home/garox/node_modules/dbus-native/node_modules/abstract-socket/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/garox/node_modules/dbus-native/node_modules/abstract-socket/lib/abstract_socket.js:4:34)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "dark-flat-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
dark-flat-ui, v1.1.4
minimap, v4.9.4
spotify-linux, v0.3.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
How did you encounter this error? Did the package work before? Is it reproducible?

**Comment by Yhozen** [comment]
1. When i started atom with the package for the first time 
2. No 
3. I can't know now
   But anyway, i'm glad that someone is making good packages for linux :D

**Comment by jazzpi** [comment]
This might be related to TooTallNate/node-bindings#17... In a terminal, could you please run

``` bash
cd ~/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket
node -e "console.log(require.resolve('bindings'))"
```

and post the output here?

**Comment by Yhozen** [comment]
/home/garox/.atom/packages/spotify-linux/node_modules/dbus-native/node_modules/abstract-socket/node_modules/bindings/bindings.js

That was the outpost :S Sorry for late response

**Comment by jazzpi** [comment]
Huh, strange.

Did you already try un- and reinstalling `spotify-linux`? That's the only thing I can think of at the moment.
