### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by danvalang** [jazzpi/spotify-linux#8]
[Enter steps to reproduce below:]
1. Execute spotify while atom is open
2. Reproduce a song different than the one the plugin is tracking

**Atom Version**: 0.208.0
**System**: Ubuntu 14.04.2
**Thrown From**: [spotify-linux](https://github.com/jazzpi/spotify-linux) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /home/dvalle/.atom/packages/spotify-linux/lib/spotify-view.coffee:27

TypeError: Cannot read property 'slice' of undefined
  at SpotifyView.module.exports.SpotifyView.update (/home/dvalle/.atom/packages/spotify-linux/lib/spotify-view.coffee:27:27)
  at /home/dvalle/.atom/packages/spotify-linux/lib/spotify-linux.coffee:33:15
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at SpotifyState.module.exports.SpotifyState.parsePlaybackStatus (/home/dvalle/.atom/packages/spotify-linux/lib/spotify-state.coffee:98:16)
  at Object.<anonymous> (/home/dvalle/.atom/packages/spotify-linux/lib/spotify-state.coffee:68:12)
  at EventEmitter.<anonymous> (/home/dvalle/.atom/packages/spotify-linux/node_modules/dbus-native/lib/bus.js:113:26)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)
  at /home/dvalle/.atom/packages/spotify-linux/node_modules/dbus-native/index.js:98:12
  at Socket.<anonymous> (/home/dvalle/.atom/packages/spotify-linux/node_modules/dbus-native/lib/message.js:53:9)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:163:7)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:402:7)
  at readableAddChunk (_stream_readable.js:157:11)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "clipboard-history",
      "jscrambler",
      "esformatter",
      "jsformat",
      "linter-jscs",
      "jshint",
      "atom-minjs",
      "term",
      "term",
      "term",
      "term",
      "Tern",
      "swap-panes"
    ]
  },
  "spotify-linux": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.2
atom-ternjs, v0.6.4
autocomplete-paths, v1.0.2
change-case, v0.6.0
color-picker, v2.0.4
docblockr, v0.7.2
docs-snippets, v0.8.0
editorconfig, v1.0.0
emmet, v2.3.10
grunt-runner, v0.10.0
highlight-selected, v0.9.3
javascript-snippets, v1.0.0
js-patterns-atom-snippets, v0.2.1
linter, v0.12.7
linter-csslint, v0.0.13
linter-jshint, v0.1.6
markdown-preview-plus, v1.5.0
mathjax-wrapper, v0.1.0
minimap, v4.9.4
minimap-git-diff, v4.1.3
mocha-test-runner, v0.4.2
node-debugger, v1.0.5
project-manager, v1.15.10
react, v0.12.0
script-runner, v1.8.3
seti-syntax, v0.4.0
seti-ui, v0.7.1
spotify-linux, v0.3.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by jazzpi** [comment]
This should be fixed in v0.3.1, can you test this again please?

**Comment by jazzpi** [comment]
Bump - can you please update spotify-linux to v0.3.1 and test whether this issue still occurs?

**Comment by danvalang** [comment]
Yes it's working right now

**Comment by jazzpi** [comment]
Alright, great! Thanks for reporting this.
